# Site settings
title: I develop tomorrow
email: mcun00@gmail.com
description: "Principal AD Tech Engineer, Continuous Delivery & Cross Device Expert, Always Thinking of Productivity and Efficiency."
baseurl: ""
url: "http://mcun0s.github.com"
twitter_username: mcunos
github_username:  mcun0s

# Build settings
markdown: kramdown
permalink: pretty
